export const FrontPermissionsConstants = {
    CAN_SHOW_APPOINTMENTS_MENU: 'CAN_SHOW_APPOINTMENTS_MENU', // CLIENTE E PROVIDER
    CAN_SHOW_MESSAGES_MENU: 'CAN_SHOW_MESSAGES_MENU', // CLIENTE E PROVIDER
    CAN_SHOW_DOCUMENTS_MENU: 'CAN_SHOW_DOCUMENTS_MENU', // PROVIDER
    CAN_SHOW_SERVICES_MENU: 'CAN_SHOW_SERVICES_MENU', // PROVIDER
    CAN_SHOW_CLIENTS_MENU: 'CAN_SHOW_CLIENTS_MENU', // CLIENTE
    CAN_SHOW_PROVIDERS_MENU: 'CAN_SHOW_PROVIDERS_MENU', // PROVIDER
    CAN_UPDATE_PROFILE: 'CAN_UPDATE_PROFILE', // CLIENTE E PROVIDER
    CAN_SHOW_HOME_DASHBOARDS: 'CAN_SHOW_HOME_DASHBOARDS', // PROVIDER
    CAN_SHOW_HOME_DEFAULT: 'CAN_SHOW_HOME_DEFAULT', // CLIENTE
    CAN_SHOW_DIAGRAM_UML: 'CAN_SHOW_DIAGRAM_UML' // PROVIDER ADMIN
}
